[mysql]    
    [mysql.mysql_w]
        host = "127.0.0.1"
        port = 3306
        username = "root"
        password = "123"
        schema = "test"
    [mysql.mysql_r]
        host = "127.0.0.1"
        port = 3306
        username = "root"
        password = "123"
        schema = "test"