name = "default.log"
dir = "/Users/liuyong/go/src/logs"
level = "info"
prefix = "yong"
max_size = 500
max_age = 1 
max_backup = 10
interval = 24
caller_skip = 1
add_caller = false
async = true
queue = false
queue_sleep = 100